[package]
name = "common-cli"
description = "The `common` command-line tool for Common Browser"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "common"
path = "src/main.rs"

[dependencies]
common-core = { path = "../common-core" }
